app:
  jwt:
    secret: ${JWT_SECRET}
    subject: true-review-api
    issuer: Soneech
    ttl: 3600
  roles:
    admin: ROLE_ADMIN
    user: ROLE_USER

spring:
  application:
    name: true-review-api

  datasource:
    url: jdbc:postgresql://localhost:5433/true_review
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
